# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 22:02
from __future__ import unicode_literals

import WebApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('folder', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(blank=True, choices=[('1', 'Important'), ('2', 'Warning'), ('3', 'Unknown')], max_length=1)),
                ('docfile', models.FileField(upload_to=WebApp.models.generate_filename)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
