# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending2CompletedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskpending',
            name='pending_task',
        ),
        migrations.RemoveField(
            model_name='taskpending',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='taskpending',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='TaskPending',
        ),
    ]
