# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
