# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20160324_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folder_description',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebApp.Label'),
        ),
    ]
