# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20160221_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField(max_length=200)),
                ('creat_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_file_address', models.CharField(max_length=100)),
                ('output_file_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=18)),
                ('display_name', models.CharField(max_length=18)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.User'),
        ),
    ]
